### ISSUE TITLE
Install error on OS X

### ISSUE THREAD

**Issue by matthewwithanm** [joaomoreno/node-libarchive#1]
Hi! I'm trying to use your [gulp-atom-shell](https://github.com/joaomoreno/gulp-atom-shell) but this library won't build correctly. Here's the relevant error. Any help would be appreciated.

```
> libarchive@0.0.5 install /path/to/node_modules/libarchive
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz
node-pre-gyp http 403 https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz (falling back to source compile with node-gyp) 
child_process: customFds option is deprecated, use stdio instead.
gyp: binding.gyp not found (cwd: /path/to/node_modules/libarchive) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/mjt/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/Users/mjt/.nvm/v0.11.14/bin/node" "/Users/mjt/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=libarchive" "--configuration=Release" "--module_name=archive" "--version=0.0.5" "--patch=5" "--runtime=node" "--node_abi=node-v0.11.14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=index.js" "--host=https://node-libarchive.s3.amazonaws.com/" "--module_path=/path/to/node_modules/libarchive/lib" "--module=/path/to/node_modules/libarchive/lib/archive.node" "--package_name=archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz" "--staged_tarball=build/stage/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz" "--hosted_path=https://node-libarchive.s3.amazonaws.com/" "--hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz"
gyp ERR! cwd /path/to/node_modules/libarchive
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/mjt/.nvm/v0.11.14/bin/node /Users/mjt/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=libarchive --configuration=Release --module_name=archive --version=0.0.5 --patch=5 --runtime=node --node_abi=node-v0.11.14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=index.js --host=https://node-libarchive.s3.amazonaws.com/ --module_path=/path/to/node_modules/libarchive/lib --module=/path/to/node_modules/libarchive/lib/archive.node --package_name=archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz --staged_tarball=build/stage/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz --hosted_path=https://node-libarchive.s3.amazonaws.com/ --hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/path/to/node_modules/libarchive/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1072:5)
node-pre-gyp ERR! System Darwin 14.0.0
node-pre-gyp ERR! command "node" "/path/to/node_modules/libarchive/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /path/to/node_modules/libarchive
node-pre-gyp ERR! node -v v0.11.14
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
Failed to execute '/Users/mjt/.nvm/v0.11.14/bin/node /Users/mjt/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=libarchive --configuration=Release --module_name=archive --version=0.0.5 --patch=5 --runtime=node --node_abi=node-v0.11.14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=index.js --host=https://node-libarchive.s3.amazonaws.com/ --module_path=/path/to/node_modules/libarchive/lib --module=/path/to/node_modules/libarchive/lib/archive.node --package_name=archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz --staged_tarball=build/stage/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz --hosted_path=https://node-libarchive.s3.amazonaws.com/ --hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v0.11.14-darwin-x64.tar.gz' (1)
npm ERR! libarchive@0.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libarchive@0.0.5 install script.
npm ERR! This is most likely a problem with the libarchive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls libarchive
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/Users/mjt/.nvm/v0.11.14/bin/npm" "install" "libarchive"
npm ERR! cwd /path/to
npm ERR! node -v v0.11.14
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /path/to/npm-debug.log
npm ERR! not ok code 0
```

**Comment by joaomoreno** [comment]
The build process is still a bit tricky, so I am now publishing the builds for the several platforms so people don't have to build them. Unfortunately, I didn't publish any for Node v0.11.

I want to cleanup the build process so people can start building this themselves. Stay tuned.

**Comment by blvz** [comment]
+1

FWIW, I've created [gulp-vinyl-yazl](https://github.com/blvz/gulp-vinyl-yazl), forked from [gulp-vinyl-zip](https://github.com/joaomoreno/gulp-vinyl-zip), which uses [yazl](https://github.com/thejoshwolfe/yazl)/[yauzl](https://github.com/thejoshwolfe/yauzl) instead of [libarchive](https://github.com/joaomoreno/node-libarchive). Sure it won't be as fast, but it's nice to have a pure JavaScript alternative.

It's working fine on OS X with node v0.11. :+1:

**Comment by joaomoreno** [comment]
This sounds very promising, I'll give it a spin.

## 

João

**Comment by blvz** [comment]
If it's taking you time to fix `libarchive`, I think it can be a drop-in replacement over `gulp-vinyl-zip` to fix `gulp-atom-shell`. If you want, of course. I still prefer `libarchive`. :)

**Comment by joaomoreno** [comment]
@blvz after a quick test drive, [yazl](https://github.com/thejoshwolfe/yazl) and [yauzl](https://github.com/thejoshwolfe/yauzl) proved to be perfect replacements for [libarchive](https://github.com/joaomoreno/node-libarchive)! :+1: 

I adopted them in [gulp-vinyl-zip](https://github.com/joaomoreno/gulp-vinyl-zip) and consumed that version in [gulp-atom-shell](https://github.com/joaomoreno/gulp-atom-shell), which is the main reason [node-libarchive](https://github.com/joaomoreno/node-libarchive) was created.

I will stop maintaining this project and redirect people to [yazl](https://github.com/thejoshwolfe/yazl)/[yauzl](https://github.com/thejoshwolfe/yauzl). Thanks for your work!

**Comment by blvz** [comment]
You're welcome. I'm glad I could help.
