### ISSUE TITLE
Install breaks within a Travis VM

### ISSUE THREAD

**Issue by nullstyle** [joaomoreno/node-libarchive#2]
A snippet from the failed install:

``` shell
> libarchive@0.0.5 install /home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive
> node-pre-gyp install --fallback-to-build
[libarchive] Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib/archive.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile 
gyp: binding.gyp not found (cwd: /home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab090.5
gyp ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=libarchive" "--configuration=Release" "--module_name=archive" "--version=0.0.5" "--patch=5" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=index.js" "--host=https://node-libarchive.s3.amazonaws.com/" "--module_path=/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib" "--module=/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib/archive.node" "--package_name=archive-v0.0.5-node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/archive-v0.0.5-node-v11-linux-x64.tar.gz" "--hosted_path=https://node-libarchive.s3.amazonaws.com/" "--hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v11-linux-x64.tar.gz"
gyp ERR! cwd /home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/v0.10.36/bin/node /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=libarchive --configuration=Release --module_name=archive --version=0.0.5 --patch=5 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=index.js --host=https://node-libarchive.s3.amazonaws.com/ --module_path=/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib --module=/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib/archive.node --package_name=archive-v0.0.5-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/archive-v0.0.5-node-v11-linux-x64.tar.gz --hosted_path=https://node-libarchive.s3.amazonaws.com/ --hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive
node-pre-gyp ERR! node -v v0.10.36
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/v0.10.36/bin/node /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=libarchive --configuration=Release --module_name=archive --version=0.0.5 --patch=5 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=index.js --host=https://node-libarchive.s3.amazonaws.com/ --module_path=/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib --module=/home/travis/build/stellar/mcs/node_modules/gulp-atom-shell/node_modules/gulp-vinyl-zip/node_modules/libarchive/lib/archive.node --package_name=archive-v0.0.5-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/archive-v0.0.5-node-v11-linux-x64.tar.gz --hosted_path=https://node-libarchive.s3.amazonaws.com/ --hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.5-node-v11-linux-x64.tar.gz' (1)
```

Travis uses glibc 2.15.

**Comment by joaomoreno** [comment]
Unfortunately this project's development has stopped.

For a good (un)zip library alternative, I suggest [yazl](https://github.com/thejoshwolfe/yazl)/[yauzl](https://github.com/thejoshwolfe/yauzl).
