### ISSUE TITLE
Compile fails on io.js

### ISSUE THREAD

**Issue by ponychicken** [joaomoreno/node-libarchive#4]
Output:

```
> libarchive@0.0.6 install /Users/leo/note/node_modules/libarchive
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
gyp: binding.gyp not found (cwd: /Users/leo/note/node_modules/libarchive) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=libarchive" "--configuration=Release" "--module_name=archive" "--version=0.0.6" "--patch=6" "--runtime=node" "--node_abi=node-v0.11.15" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=index.js" "--host=https://node-libarchive.s3.amazonaws.com/" "--module_path=/Users/leo/note/node_modules/libarchive/lib" "--module=/Users/leo/note/node_modules/libarchive/lib/archive.node" "--package_name=archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz" "--staged_tarball=build/stage/archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz" "--hosted_path=https://node-libarchive.s3.amazonaws.com/" "--hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz"
gyp ERR! cwd /Users/leo/note/node_modules/libarchive
gyp ERR! node -v v0.11.15
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=libarchive --configuration=Release --module_name=archive --version=0.0.6 --patch=6 --runtime=node --node_abi=node-v0.11.15 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=index.js --host=https://node-libarchive.s3.amazonaws.com/ --module_path=/Users/leo/note/node_modules/libarchive/lib --module=/Users/leo/note/node_modules/libarchive/lib/archive.node --package_name=archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz --staged_tarball=build/stage/archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz --hosted_path=https://node-libarchive.s3.amazonaws.com/ --hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/leo/note/node_modules/libarchive/node_modules/node-pre-gyp/lib/util/compile.js:71:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/leo/note/node_modules/libarchive/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/leo/note/node_modules/libarchive
node-pre-gyp ERR! node -v v0.11.15
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=libarchive --configuration=Release --module_name=archive --version=0.0.6 --patch=6 --runtime=node --node_abi=node-v0.11.15 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=index.js --host=https://node-libarchive.s3.amazonaws.com/ --module_path=/Users/leo/note/node_modules/libarchive/lib --module=/Users/leo/note/node_modules/libarchive/lib/archive.node --package_name=archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz --staged_tarball=build/stage/archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz --hosted_path=https://node-libarchive.s3.amazonaws.com/ --hosted_tarball=https://node-libarchive.s3.amazonaws.com/archive-v0.0.6-node-v0.11.15-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "libarchive"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! libarchive@0.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libarchive@0.0.6 install script.
npm ERR! This is most likely a problem with the libarchive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls libarchive
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/leo/note/npm-debug.log
```

https://github.com/iojs/io.js/issues/456

**Comment by joaomoreno** [comment]
Unfortunately this project's development has stopped.

For a good (un)zip library alternative, I suggest [yazl](https://github.com/thejoshwolfe/yazl)/[yauzl](https://github.com/thejoshwolfe/yauzl).
